### ISSUE TITLE
Where is example.env?

### ISSUE THREAD

**Issue by SurajRaj4542** [callsmusic/CallsMusicRemix#1]
as you said: `Copy example.env to .env and fill it with your credentials.`
but where is example.env?

**Comment by rojserbest** [comment]
Hehe, finally someone who reads the README.

**Comment by rojserbest** [comment]
There's None, but you can add it following [here](https://github.com/callsmusic/CallsMusicRemix/blob/main/src/env.ts)...

**Comment by SurajRaj4542** [comment]
So, I can make changes in env.ts or add a .env file by following that

**Comment by rojserbest** [comment]
Add an exampleenv following that. You can send a PR too if you like to contribute.
